{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flechazo",
    "module": "jzxlib",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jzxlib-0.0.2.jar",
          "url": "jzxlib-0.0.2.jar",
          "size": 10347710,
          "sha512": "79365cca7e71afb06c2d4c7ad942fab6aea3000acda8522015c42724de4a2c1b771aac3ae2b15a89502b8f21702dae2d45592c2d7d032031339b10a2845fe6b5",
          "sha256": "d324db324a396ac3e226f43f00b03a6e6d62dc5ac0ea6b8d00f97756e86af071",
          "sha1": "214aaf9c0fd1a330e7bdebef6ddbda46d70285e1",
          "md5": "25d04248be997a3d1311d7f5d052ce17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.5+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "recipe_book_categories",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registries",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_builders",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_generators",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_materials",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "utility",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "level_events",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "jzxlib-0.0.2.jar",
          "url": "jzxlib-0.0.2.jar",
          "size": 10347710,
          "sha512": "79365cca7e71afb06c2d4c7ad942fab6aea3000acda8522015c42724de4a2c1b771aac3ae2b15a89502b8f21702dae2d45592c2d7d032031339b10a2845fe6b5",
          "sha256": "d324db324a396ac3e226f43f00b03a6e6d62dc5ac0ea6b8d00f97756e86af071",
          "sha1": "214aaf9c0fd1a330e7bdebef6ddbda46d70285e1",
          "md5": "25d04248be997a3d1311d7f5d052ce17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jzxlib-0.0.2-sources.jar",
          "url": "jzxlib-0.0.2-sources.jar",
          "size": 7471,
          "sha512": "7934aef22d27ef77e5533b4c46dc87866ed598ca7650dbafda9ba1e38f7d678fb319a9345f8cd97b6cfaa0d4dd5c9646e1cc7261a539ac123c2ee66f91d2e1f9",
          "sha256": "73281fd47083bf7572ba6fbc9f69fd4600301a7c0bed397db2fccf50ad36ff6c",
          "sha1": "7128df5f427e22dd8d3f0573c6988f93f5ca5f32",
          "md5": "f24264613c43a22f8de788bcd0bdc240"
        }
      ]
    }
  ]
}
