{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flechazo",
    "module": "jzxlib",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "recipe_book_categories",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registries",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_builders",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_generators",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_materials",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "utility",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "level_events",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "jzxlib-0.0.5.jar",
          "url": "jzxlib-0.0.5.jar",
          "size": 10349359,
          "sha512": "55156ec50e6aefa7d218b831081524ccdcabad6f3f8393b7497509bee1868d76b2e8bd6f250ccf386adefe041884a41c513761898f2076afb683706b5915dcc6",
          "sha256": "2025d296010b3134731e558273985e221e8a9b486e810ac6e4bb7a39d44a2b4a",
          "sha1": "98a0c808090ef1ea1f926a9b736768aa3afa2beb",
          "md5": "24a2b04d91534903097de7e994a3ae60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "recipe_book_categories",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registries",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_builders",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_generators",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_materials",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "utility",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "level_events",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.5+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "jzxlib-0.0.5.jar",
          "url": "jzxlib-0.0.5.jar",
          "size": 10349359,
          "sha512": "55156ec50e6aefa7d218b831081524ccdcabad6f3f8393b7497509bee1868d76b2e8bd6f250ccf386adefe041884a41c513761898f2076afb683706b5915dcc6",
          "sha256": "2025d296010b3134731e558273985e221e8a9b486e810ac6e4bb7a39d44a2b4a",
          "sha1": "98a0c808090ef1ea1f926a9b736768aa3afa2beb",
          "md5": "24a2b04d91534903097de7e994a3ae60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jzxlib-0.0.5-sources.jar",
          "url": "jzxlib-0.0.5-sources.jar",
          "size": 8574,
          "sha512": "37e1e53c140998d902a79a349f1e65ce43c8bfdd4ea61d150b7f814f3df67258b51ea43711b38d175f6c50ff5dfc89ca9a94e1d71741b8022f7b964dccddbc9d",
          "sha256": "1e9bc468d3a4215655c7b368634f0e533be940340a1c4de9b74e94f94e71dd9f",
          "sha1": "e2aadda21a63ebae981443e3c8db8b56c6185d0b",
          "md5": "3bd662388acb40125035996ad3515ea8"
        }
      ]
    }
  ]
}
